### ISSUE TITLE
Photon not cropping correctly

### ISSUE THREAD

**Issue by lmartins** [slimndap/TimberPhoton#3]
Im having a few issues with Photon and Timber, where Photon does resize images but doesn't respect the hard crop it was supposed to happen.

Considering the following page as an example:
http://outline.webipack.com/services/

All images were supposed to be 320x240px, with hard crop, but what is happening is that some are taller, some are shorter, can't get them all to have the same height.

Have you noticed this behaviour before?

Update:
I just noticed that the query that is being passed to Photon is:
```
<img src="http://i0.wp.com/www.webipack.com/mw-public/uploads/sites/24/2015/01/Depositphotos_4459897_original2.jpg?fit=320%2C240">
```

The API however says that for hard-cropping this is what should be done:
```
<img src="http://i0.wp.com/www.webipack.com/mw-public/uploads/sites/24/2015/01/Depositphotos_4459897_original2.jpg?resize=320,240">
```

Any way I can achieve that?

**Comment by lmartins** [comment]
Ok, this actually results from my incorrect assumption that the plugin would also work with Wordpress's media sizes vars
```
{{ post.thumbnail.src('medium') }}
``` 

That obviously isn't the case. 
Quick question though, how could you pass a Twig variable to the filter?

I've tried with `<img src="{{ post.thumbnail.src|resize(thumbsize) }}" />` but sadly doesn't work.

Thanks.

**Comment by slimndap** [comment]
Hi! Thanks for using my plugin.
I'm really interested in your feedback, so I can improve this plugin.

> Quick question though, how could you pass a Twig variable to the filter?
> I've tried with `<img src="{{ post.thumbnail.src|resize(thumbsize) }}" />` but sadly doesn't work.

I'm not sure. Does this work when you're not using TimberPhoton (just Timber)?

**Comment by lmartins** [comment]
Hey Jeroen, 

Let me be the one giving thanks, for making the plugin available.
Is was passing the variable incorrectly, it expects an array and I was passing the array value as a string.

Thanks again.
